website/auth.py
#authentication for logon to the web application

from flask import (Blueprint, flash, render_template, request, url_for, redirect) 
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user, current_user
from . import db

#create a blueprint
bp = Blueprint('auth', __name__)

#login
@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error=None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        #if there is no user with that name
        if u1 is None:
            error='Incorrect user name, Please try again.'
        #check the password - notice password hash function
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password, Please try again.'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(u1)
            nextp = request.args.get('next') #this gives the url from where the login page was accessed
            print(nextp)
            if nextp is None or not nextp.startswith('/'):
                return redirect(url_for('main.index'))
            return redirect(nextp)
        else:
            flash(error, 'login_error')
    return render_template('user.html', form=login_form, heading='Login')



#register
@bp.route('/register', methods=['GET','POST'])
def register():
    register = RegisterForm()
    if register.validate_on_submit():
        uname = register.user_name.data
        pwd = register.password.data
        email = register.email_id.data
        number = register.contact_number.data
        address = register.address.data
        message = 'Registered Successfully'
        # Check if the user name already exists
        u1 = User.query.filter_by(name=uname).first()
        if u1:
            flash('User name already exists. Please login.', 'register_error')
            return redirect(url_for('auth.login'))
        email1 = User.query.filter_by(emailid = email).first()
        if email1:
            flash('This email address has been registered. Please try again.', 'register_error')
            return redirect(url_for('auth.login'))
        
        # Generate a password hash to store and commit the new user to the database
        pwd_hash = generate_password_hash(pwd)
        new_user = User(name=uname, password_hash=pwd_hash, emailid=email, contact_number=number, address=address)
        db.session.add(new_user)
        db.session.commit()
        flash(message, 'register_error')
        return redirect(url_for('auth.login'))

    else:    
        return render_template('user.html', form=register, heading='Register')

#logout
@bp.route("/logout", methods=['GET','POST'])
@login_required
def logout():
    """Logout the current user."""
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for('main.index'))

website/views.py
from flask import Blueprint, render_template, request, redirect,url_for, flash
from .models import Event, Event_Status

mainbp = Blueprint('main', __name__)
#create sqlite query to select each category, example rockCategory = Event.query.filter(Event.category.like("Rock")).all()
#this will create a list of events for each category 
#this query can be used any time we want to show events by category - can then take out the jinja2 if statement 
#which is calling the event variable which returns all of the events in the database
@mainbp.route('/')
def index():
    event = Event.query.all()
    #category = Event.query.filter(Event.category).all()
    rockEvent = Event.query.filter(Event.category.like("Rock")).all()
    popEvent = Event.query.filter(Event.category.like("Pop")).all()
    jazzEvent = Event.query.filter(Event.category.like("Jazz")).all()
    return render_template('index.html', event = event, rockEvent = rockEvent, popEvent = popEvent, jazzEvent = jazzEvent) #rockCategory = rockCategory then call in html jinja2 template in for loop

@mainbp.route('/category')
def category():
    event = Event.query.all()
    rockEvent = Event.query.filter(Event.category.like("Rock")).all()
    popEvent = Event.query.filter(Event.category.like("Pop")).all()
    jazzEvent = Event.query.filter(Event.category.like("Jazz")).all()
    countryEvent = Event.query.filter(Event.category.like("Country")).all()
    electronicEvent = Event.query.filter(Event.category.like("Electronic")).all()
    funkEvent = Event.query.filter(Event.category.like("Funk")).all()
    reggaeEvent = Event.query.filter(Event.category.like("Reggae")).all()
    heavyEvent = Event.query.filter(Event.category.like("Heavy Metal")).all()
    rythemEvent = Event.query.filter(Event.category.like("Rhythm and Blues")).all()
    return render_template('category.html', event = event, rockEvent = rockEvent, popEvent = popEvent, jazzEvent = jazzEvent, countryEvent = countryEvent, electronicEvent = electronicEvent,
    funkEvent = funkEvent, reggaeEvent = reggaeEvent, heavyEvent = heavyEvent, rythemEvent = rythemEvent) 

@mainbp.route('/search',  methods=['GET', 'POST'])
def search():
    if request.args['search']:
        print(request.args['search'])
        dest = "%" + request.args['search'] + '%'
        event = Event.query.filter(Event.description.like(dest) | Event.category.like(dest) | Event.name.like(dest)).all()
        flash(dest.replace("%",""), 'search_error')
        return render_template('search.html', event=event)
    else:
        flash("No Results Found.", 'search_error')
        return redirect(url_for('main.index'))

@mainbp.route('/help')
def help():
    return render_template('help.html') 

@mainbp.route('/thankyou')
def thankyou():
    return render_template('thankyou.html') 

website/templates/base.html
<!DOCTYPE html>
<html>  
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheet/stylesheet.css') }}">
        <link rel='icon' href="{{ url_for('static', filename='image/favicon.ico') }}" type='image/x-icon' sizes="16x16" > 
        
        <!-- Title Text -->
        <title>MusicEvents</title>
       
    </head>
    <body>
        <header>
            <!--NavBar-->
            <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
                <div class="container-fluid">
                    <a class="navbar-brand changeFont" href="/">MusicEvents</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle " href="#" id='CatBar' role="button" data-bs-toggle="dropdown" aria-expanded="false"><strong>Book Now</strong></a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/category">View All Categories</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="/">Popular Events</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link" href="{{ url_for('events.booking_history') }}" id = 'CatBar'><strong>Booking History</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('events.create') }}" id = 'CatBar'><strong>Create New Event</strong></a>
                        </li>
                        <!-- my event-->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('events.my_events') }}" id = 'CatBar'><strong>MyEvents</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/help" id = 'CatBar'>Help</a>
                        </li>
                        </ul>
                        <form class="d-flex">
                            <!-- Register/Login/Logout and welcome -->
                            {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link  text-light disabled" href="#">Welcome {{current_user.name}}</a>
                            <a class="nav-item nav-link btn-danger text-light rounded " href="{{ url_for('auth.logout') }}">Log Out</a>
                            {% else %}
                            <a class="nav-item nav-link text-light margin3" href="{{ url_for('auth.register') }}">Register</a>
                            <a class="nav-item nav-link btn-primary text-light rounded" href="{{ url_for('auth.login') }}"><b>Log In</b></a>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </nav>
            {% block header %}
            {% endblock %}
        </header>
            {% block content %}
            {% endblock %}
        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
        -->
    </body>

    <footer class=" text-center text-muted"> <br>Terms and Conditions: </br> In lacinia nibh a mi tempor consectetur. Fusce posuere vehicula mauris, quis
     placerat nisl egestas in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque cursus tempor. Aenean sodales urna eu accumsan mattis. Pellentesque a
      congue quam. Maecenas tempus lectus efficitur maximus sodales. Duis ut metus in elit commodo ullamcorper. Duis volutpat placerat lacus, quis vestibulum diam tempor in. In et cursus orci,
       ac placerat sem. Curabitur laoreet dui quam, eu pretium nisi posuere quis. Cras vitae erat eget risus posuere tempor. Maecenas pulvinar lorem et libero dictum scelerisque. Cras pellentesque
        eget odio vel volutpat. Integer viverra iaculis justo, eu imperdiet justo scelerisque quis. Curabitur sodales nibh in ante tristique, vitae efficitur odio mollis.
       <h6 class = "text-center lead">Copyright - MusicEvents 2021.</h6>
    </footer>
</html>

website/templates/help.html
{% extends 'base.html' %}

{% block header %}
    
    
    <!-- Help details -->
    <div class="jumbotron text-center">
        <h1 class="display-3">Contact Us</h1>
        <p class="lead">Having trouble? Contact us at <strong>MusicEvents@gmail.com</strong></p>
        <hr>

        <p class="lead">
          <a class="btn btn-primary btn-sm" href="/" role="button">Continue to homepage</a>
        </p>
      </div>

{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block header %}
        {% with messages = get_flashed_messages(category_filter=["delete"]) %}
        {% if messages %}
        <div class="container-fluid margin pad">
            {% for message in get_flashed_messages() %}
            <div class ="alert alert-warning">
                <button type="button" class="close btn-success" data-dismiss="alert" aria-label="close">x</button>
                {{message}}
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
        
          <!--Jumbotron-->
          <div class=".p-sm-5 mb-4 bg-light rounded-3 card2">
            <div class="jumbotronback container-fluid py-5">
            {% for event in event %}
            {% if event.id ==  1 %}
                <h1 class="display-5 fw-bold text-white customOutline">Upcoming Music Event:</h1>
                <h4 class="display-5 fw-bold text-warning changeFont customOutline">{{event.name}}</h4>
                    <p id = JumboPara class="col-md-8 fw-bold text-white fs-4 bg-dark rounded-3">{{event.description}}</p>
                    <a href="{{url_for('events.show', id=event.id)}}" class="btn btn-primary margin3">Find Tickets</a>
            </div>
        </div>
            {% endif %}
            {% endfor %}

{% endblock %}
   
{% block content %} 

        
        <!--Welcome Message-->
        <h1 class = "text-center">Welcome to the MusicEvents Website! </h1>
        <!--Seach All Music text-->
        <h6 class = "text-center">Search All Music </h6>


        <div class="container-fluid">

            <form class="form-inline d-flex flex-nowrap" id = searchbar action="{{url_for('main.search')}}" >
                <input type="text" name="search" class="pad2 form-control flex-grow-1 my-1 mr-sm-2 a margin3" id="innerSearchBar">
                <button type="submit" class="flex-shrink-1 btn btn-primary my-1">&#128269</button>
            </form>
            <!--Search by Catergoy text-->
            <h6 class = "text-center ">Search Popular Categories </h6>

             <!--Catergory Nav Bar-->
             <ul class="margin nav justify-content-center">
                <li class="nav-item bg-dark rounded-3 nav2li">
                  <a class="nav-link active btn-lg" href="#rock" id = 'CatBar'>Rock</a>
                </li>
                <li class="nav-item bg-dark rounded-3 nav2li">
                  <a class="nav-link btn-lg" href="#pop" id = 'CatBar'>Pop</a>
                </li>
                <li class="nav-item bg-dark rounded-3 nav2li">
                  <a class="nav-link btn-lg" href="#jazz" id = 'CatBar'>Jazz</a>
                </li>
            </ul>
            
            <hr>

            <!--Row 1 ROCK category-->
            <h2 class = "text-center margin4 backgroundCustom3 card center border-secondary" id="rock"><b>Rock Music Events</b></h2>
            <div class="row">
                {% for rockEvent in rockEvent  %}
                <div class="col-12 col-lg-4 col-md-4 col-sm-4 card center margin4" style="width: 30rem;">
                    <img src="{{rockEvent.image}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h4 class="card-title">{{rockEvent.name}}</h4>
                        {% for rockEvent in rockEvent.status %}
                        {% if rockEvent.status == "Upcoming" %}
                        <h6 class="card-title text-info">Status: {{rockEvent.status}}</h6>
                        {% elif rockEvent.status == "Booked" %}
                        <h6 class="card-title text-danger">Status: {{rockEvent.status}}</h6>
                        {% elif rockEvent.status == "Canceled" %}
                        <h6 class="card-title text-warning">Status: {{rockEvent.status}}</h6>
                        {% elif rockEvent.status == "Inactive" %}
                        <h6 class="card-title text-secondary">Status: {{rockEvent.status}}</h6>
                        {% endif %}
                        {% endfor %}
                        <p class="card-text">{{rockEvent.description}}</p>
                        <a href="{{url_for('events.show', id=rockEvent.id)}}" class="btn btn-primary">Find Tickets</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <hr>

            
            <!--Row 2 POP category-->
            <h2 class = "text-center margin4 backgroundCustom3 card center border-secondary" id="pop"><b>Pop Music Events</b></h2>
            <div class="row">
                {% for popEvent in popEvent  %}
                <div class="col-12 col-lg-4 col-md-4 col-sm-4 card center margin4" style="width: 30rem;">
                    <img src="{{popEvent.image}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h4 class="card-title">{{popEvent.name}}</h4>
                        {% for popEvent in popEvent.status %}
                        {% if popEvent.status == "Upcoming" %}
                        <h6 class="card-title text-info">Status: {{popEvent.status}}</h6>
                        {% elif popEvent.status == "Booked" %}
                        <h6 class="card-title text-danger">Status: {{popEvent.status}}</h6>
                        {% elif popEvent.status == "Canceled" %}
                        <h6 class="card-title text-warning">Status: {{popEvent.status}}</h6>
                        {% elif popEvent.status == "Inactive" %}
                        <h6 class="card-title text-secondary">Status: {{popEvent.status}}</h6>
                        {% endif %}
                        {% endfor %}
                        <p class="card-text">{{popEvent.description}}</p>
                        <a href="{{url_for('events.show', id=popEvent.id)}}" class="btn btn-primary">Find Tickets</a>
                    </div>
                </div>
                {% endfor %}
            </div>

            <hr>

            
            <!--Row 3 Jazz category-->
            <h2 class = "text-center margin4 backgroundCustom3 card center border-secondary" id="jazz"><b>Jazz Music Events</b></h2>
            <div class="row">
                {% for jazzEvent in jazzEvent %}
                <div class="col-12 col-lg-4 col-md-4 col-sm-4 card center margin4" style="width: 30rem;">
                    <img src="{{jazzEvent.image}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h4 class="card-title">{{jazzEvent.name}}</h4>
                        {% for jazzEvent in jazzEvent.status %}
                        {% if jazzEvent.status == "Upcoming" %}
                        <h6 class="card-title text-info">Status: {{jazzEvent.status}}</h6>
                        {% elif jazzEvent.status == "Booked" %}
                        <h6 class="card-title text-danger">Status: {{jazzEvent.status}}</h6>
                        {% elif jazzEvent.status == "Canceled" %}
                        <h6 class="card-title text-warning">Status: {{jazzEvent.status}}</h6>
                        {% elif jazzEvent.status == "Inactive" %}
                        <h6 class="card-title Custom2">Status: {{jazzEvent.status}}</h6>
                        {% endif %}
                        {% endfor %}
                        <p class="card-text">{{jazzEvent.description}}</p>
                        <a href="{{url_for('events.show', id=jazzEvent.id)}}" class="btn btn-primary">Find Tickets</a>
                    </div>
                </div>
                {% endfor %}
            </div>

            <hr>
            <div class = "col text-center pad">
                <a href="/category" class="btn text-center buttonCustom2 border-secondary">Search All Categories</a>
            </div>
            <div class = "col text-center margin pad">
                <a href="/" class="btn text-center btn-secondary border-secondary">Back to top</a>
            </div>
            
{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<style>
    #searchbar {
    margin: 0 auto;
    display: block;
    width: 80%;
}
</style>
    <div class="container-fluid backgroundCustom margin4">
        <h3 class = "pad">Search Events</h3>
        <div class = " ">
            <form class=" form-inline d-flex flex-nowrap searchbar" id = searchbar action="{{url_for('main.search')}}" >
            
                <input type="text" name="search" class="pad2 form-control flex-grow-1 my-1 mr-sm-2 a margin3" id="innerSearchBar">
                <button type="submit" class="flex-shrink-1 btn btn-primary my-1">&#128269</button>
            </form>
        </div>
        <!--get flashed messages-->
        <h3 class="pad margin1 text-center">Search Results for:
            {% with messages = get_flashed_messages(category_filter=["search_error"]) %}
        {% if messages %}
            {% for message in get_flashed_messages() %}
               <b class = "changeTextColour"><br>"{{message}}"</b>
            {% endfor %}
        {% endif %}
        {% endwith %}
        </h3>
        
        <br>
        <hr>
        <br>
        <!--display search-->
        <div class="row">
            <div class = "pad col-12 col-lg-12 col-md-12 col-sm-12 card center margin4" style="width: 60rem;">
                {% for event in event %}
                <div class="card text-center">
                    <h5 class="card-title pad"><b>{{event.name}}</b></h5>
                    <img class="img-fluid center pad" src="{{event.image}}" style="width: 53rem;">
                    <div class="card-body">
                        <h5 class="card-title ">Artist:<br> {{event.artist}}</h5>
                        {% for event in event.status %}
                        {% if event.status == "Upcoming" %}
                        <h5 class="text-center text-info "><br>Status:</br>{{event.status}}</h5>
                        {% elif event.status == "Booked" %}
                        <h5 class="text-center text-danger "><br>Status:</br>{{event.status}}</h5>
                        {% elif event.status == "Canceled" %}
                        <h5 class="text-center text-warning "><br>Status:</br>{{event.status}}</h5>
                        {% elif event.status == "Inactive" %}
                        <h5 class="text-center Custom2 "><br>Status:</br>{{event.status}}</h5>
                        {% endif %}
                        {% endfor %}
                        <h5 class="card-text pad">Category: {{event.category}}</h5>
                        <p class="card-text event-description">Description: <br>{{event.description}}</p>
                    </div>
                    <div class="card-footer"><a href = "{{url_for('events.show', id=event.id)}}" class ="btn  backgroundCustom4 "> View Details </a></div>
                </div>
                <br>
                <br>
                <hr>
                <br>
                <br>
                {% endfor %}
                {% if event|length == 0 %}
                <div class = "card center margin">
                    <h6 class="card-title text-danger text-center pad2"><b>No events Found.</b></h6>
                    <hr>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
     <!--back to top button-->
     <div class = "col text-center">
        <a href="#" class="btn text-center buttonCustom2">Back to top</a>
    </div>
{% endblock %}

website/templates/thankyou.html
{% extends 'base.html' %}

{% block header %}
<!-- get flashed messages-->
  {% with messages = get_flashed_messages(category_filter=["event_booking"]) %}
  {% if messages %}
  <div class="container-fluid margin2 pad">
      {% for message in get_flashed_messages() %}
      <div class ="alert alert-warning">
          <button type="button" class="close btn-success" data-dismiss="alert" aria-label="close">x</button>
          {{message}}
      </div>
      {% endfor %}
  {% endif %}
  {% endwith %}
  </div>
    
    <!-- Thank you details -->
    <div class="jumbotron text-center">
        <h1 class="display-3">Thank You!</h1>
        <p class="lead"><strong>Please check your email</strong> for further instructions on how to receive your tickets.</p>
        <p class="lead">
          <a class="btn btn-dark btn-sm" href="{{url_for('events.booking_history')}}" role="button">View Booking History</a>
        </p>
        <hr>
        <p>
          Having trouble? <a href="/help">Contact us</a>
        </p>
        <p class="lead">
          <a class="btn btn-primary btn-sm" href="{{url_for('main.index')}}" role="button">Continue to homepage</a>
        </p>
    </div>

{% endblock %}

website/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="page-header center pad">
    <h4>{{heading}}</h4>
</div>
<!--get flashed messages-->
<div class="container-fluid">
{% with messages = get_flashed_messages(category_filter=["register_error"]) %}
{% if messages %}
    {% for message in get_flashed_messages() %}
    <div class ="alert alert-warning">
        <button type="button" class="close btn-success" data-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
{% endif %}
{% endwith %}

{% with messages = get_flashed_messages(category_filter=["login_error"]) %}
{% if messages %}
    {% for message in get_flashed_messages() %}
    <div class ="alert alert-warning">
        <button type="button" class="close btn-success" data-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
{% endif %}
{% endwith %}
</div>

<!-- login form -->
<div class="col-md-6 center margin">
{{wtf.quick_form(form, button_map={'submit':'success'})}}
</div>

<!-- register form -->
{% if heading|lower =='login' %}
<div class="col-md-4 center margin">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}

{% endblock %}